// <auto-generated />
using AudiologyHardwareInventory.DataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AudiologyHardwareInventory.Migrations
{
    [DbContext(typeof(HardwareInventoryContext))]
    [Migration("20210803120936_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AudiologyHardwareInventory.Models.Hardware", b =>
                {
                    b.Property<int>("HardwareId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HardwareName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HardwareStatus")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HardwareId");

                    b.ToTable("HardwareDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
